spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/refresh
    username: ${your_name}
    password: ${your_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  admin-key: "adminKey"
  secret-key: "secretKey"
  access-token-expiration : 86400000
  refresh-token-expiration : 604800000
